server:
  port: 8888

spring:
  application:
    name: vid-cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vidhangithub/vid-cloud-config-repo
          default-label: main
          clone-on-start: true
